name: tri
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_core: 3.6.0  # Ensure Firebase core is added for Firebase initialization

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/triangle_image.png 
    - assets/profile_picture.png
    - assets/food1.png
    - assets/food2.png
    - assets/food3.png
    - assets/food4.png
    - assets/restaurant1.png
    - assets/restaurant2.png
    - assets/restaurant3.png
    - assets/red_sauce_pasta.png
    - assets/chocolate_cake.png
    - assets/chicken_tikka.png # Ensure this path and file exist in your project
